// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "../context/TodoContext";
import { StarProvider } from "../context/StarContext";
import Layout from '@/layout/layout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TodoProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <StarProvider>
          <Layout>
            {children}
            </Layout>
          </StarProvider>
        </body>
      </TodoProvider>
    </html>
  );
}